# Generated by Django 3.2.9 on 2021-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/sub_category'),
        ),
    ]
