# Generated by Django 3.2.9 on 2021-11-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_sub_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
